f=open('abc1.txt','r')
line1=f.readline()
print('First Name:',line1,end='')
line2=f.readline()
print('Second Name:',line2,end='')
line3=f.readline()
print('Third Name:',line3,end='')
line4=f.readline()
print('Third Name:',line4,end='')
f.close()
